export enum EVENTS {
  SHOW_ALERT = 'SHOW_ALERT',
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
  SHOW_MODAL_AVATAR = 'SHOW_MODAL_AVATAR', // 打开头像上传弹窗
  SHOW_MODAL_BASE_INFO = 'SHOW_MODAL_BASE_INFO', // 打开基础信息编辑弹窗
  SHOW_MODAL_SOCIAL_LINK = 'SHOW_MODAL_SOCIAL_LINK', // 打开“社交平台图标”弹窗
  SHOW_MODAL_ADD_SOCIAL_LINK = 'SHOW_MODAL_ADD_SOCIAL_LINK', // 打开“添加社交平台图标”弹窗
  SHOW_MODAL_SOCIAL_LINK_ICON = 'SHOW_MODAL_SOCIAL_LINK_ICON', // 打开“添加指定社交平台内容”弹窗
  SHOW_SHARE = 'SHOW_SHARE', // 打开分享弹窗
  SHOW_MOCK_UP = 'SHOW_MOCK_UP', // 打开生成海报弹窗
  SHOW_QR_CODE = 'SHOW_QR_CODE', // 打开生成 qrcode 弹窗

  UPDATE_PAGE_PREVIEW_MODAL = 'UPDATE_PAGE_PREVIEW_MODAL', // 更新预览组件下的 modal 组件

  UPDATE_MODAL_AUTH = 'UPDATE_MODAL_AUTH', // 注册登录弹窗
  UPDATE_USER_MORE = 'UPDATE_USER_MORE', // 左下角的用户更多菜单
}
